### ISSUE TITLE
How to edit Google Drive token?

### ISSUE THREAD

**Issue by OffCorner** [qdm12/stackedit-docker#1]
This is exactly what I have been looking for!
I have managed to set up Stackedit in docker now but I'd love to configure it with Google Drive.
Unfortunately, I can't seem to find any way to do this...
Any help would be greatly appreciated!

**Comment by qdm12** [comment]
Hi there,

It very looks like an issue with authorizing stackedit on a Google project. I'll open an issue on their Github for you and report back when I have an answer.

Thanks!

**Comment by moookino** [comment]
HI, @qdm12  thanks for your docker image! I think there is same issue with setting Dropbox account for selfhosted variant, where callback is needed to authorize hosted instance

**Comment by qdm12** [comment]
Hi @moookino I have finally had the chance/time to have a look, and there is now the environment variables `GOOGLE_CLIENT_ID` and `GOOGLE_API_KEY` to connect to Google. Not too sure how to use them, you probably would have to setup an app on Google. There are other environment variables for Github, Dropbox etc documented in the [readme](https://github.com/qdm12/stackedit-docker#environment-variables).

**Comment by moookino** [comment]
Hi @qdm12 thanks! It works for me.
Maybe for someone interested in the future.
You need to setup 2 things O2Auth client to use and use it's client id
Setup API key and use this key as Google API key
