### ISSUE TITLE
How do I specify where the markdown documents should be saved on my local filesystem?

### ISSUE THREAD

**Issue by nicolae-stroncea** [qdm12/stackedit-docker#9]
Thanks for packaging the project in such an accessible manner!

I would like to be able to save the documents on my local system in a directory that I can choose. What command could I run to enable that?

**Comment by qdm12** [comment]
Hi there,

Thanks for your compliment 👍 

Stackedit is only client side, so the server cannot have access to their client data.

> The local files are not stored in any directory. They are stored in the browser's localStorage accessible only via JavaScript. You can export files using save as submenu.

**HOWEVER**:

- You can sync it with i.e. Dropbox ☁️  syncing with your computer. Not ideal privacy wise, but it works.
- You can [extract the data from the localStorage](https://stackoverflow.com/a/12799050/7949869); no intermediary but it's not great either 😄
